export const homeObjOne = {
  id: "about",
  lightBg: false,
  lightText: false,
  lightTextDesc: true,
  topLine: "Professional Reuse",
  headline: "Ultimate Environmental Protection",
  description: "Get access to our Services to make Earth can be -- Rinascere.",
  buttonLabel: "Get Started",
  imgStart: false,
  img: require("../../images/svg-1.svg").default,
  alt: "Earth",
  dark: true,
  primary: true,
  darkText: true,
};

export const homeObjTwo = {
  id: "discover",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Professional Process",
  headline: "Mix the Spacial ingredients",
  description: "recycled wood + compatibilizer = FPC",
  buttonLabel: "Learn More",
  imgStart: true,
  img: require("../../images/svg-2.svg").default,
  alt: "Process",
  dark: false,
  primary: false,
  darkText: true,
};

export const homeObjThree = {
  id: "joinus",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Join Our Team",
  headline: "閉嘴！進來就對了",
  description: "我掰不下去了",
  buttonLabel: "Connect Us",
  imgStart: false,
  img: require("../../images/joinus.svg").default,
  alt: "paper",
  dark: false,
  primary: false,
  darkText: true,
};
